spring:
  application:
    name: polarproject
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/polarproject
    username: user
    password: password
#    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

